Delete Event User Story
RoyceLuo1216/CSC207 pull request #13
Opened 2024-11-24 00:08 UTC by RoyceLuo1216

Completed work on edit/delete view, and finished the delete event use case. 

note, there are currently imports on entities in editDeleteView, however, these are only used in the main function purely used to visualize and test the view for the interim. These imports will be deleted at finalization, to abide by CA.

further note, since we dont have a main class we can't use cardlayout for managing transitions between views yet, so that logic needs to be implemented still, but most of the logic is there already.

2024-11-27 04:29 UTC, venniseho commented on src/main/java/entities/EventEntity/FlexibleEvent.java
I think we can delete this file, no?

2024-11-27 04:45 UTC, venniseho requested changes
- let's not merge the incomplete files into main yet (i.e. schedule controller/presenter)
- I know we've kind of integrated your use case (delete) and mine (edit) for ease of use, but I think we should split the files for edit and delete to make it more in line with CA and SOLID principles (specifically, the single responsibility principle), but we can talk about it more
- otherwise, everything looks relatively good in relation to design principles
- please add comments! (i.e. javadoc for your methods)

2024-12-01 02:37 UTC, RoyceLuo1216 commented on src/main/java/entities/EventEntity/FlexibleEvent.java
Yea deleted

2024-12-01 03:13 UTC, utcjcao commented
1. To fix external clean architecture issues:

a) rename data_access Schedule into InMemoryDataAccessObject
b) delete data package
c) write data access interface for: delete, edit, chatbot conflicts
d) merge chris dao branch with data access branch to get the json dao (inmemory, json dao are written)

2. To fix chatbot event conflict view model:
a) update message to reflect separation of time estimation and event conflict chatbots
b) update ui to include access to time estimation 
c) merge with chris-branch-dao-v2 for time estimation usecase

3. delete event conflict output data, its unused

2024-12-01 03:41 UTC, utcjcao reviewed
some tests might need to watch out for newlines, trimming, edges cases for empty lists

also need to remove cohereparser (redundant)

2024-12-01 03:41 UTC, utcjcao commented on src/main/java/adapter/CohereParser.java
delete this file, its unused

2024-12-01 03:41 UTC, utcjcao commented on src/main/java/data/EventStorage.java
this file is renamed in main

2024-12-01 03:41 UTC, utcjcao commented on src/main/java/data/EventStorage.java
also don't forget to implement the data, edit, chatbot conflict interfaces when we make our daos

2024-12-01 03:41 UTC, utcjcao commented on src/main/java/usecase/chatbot_event_conflict/EventConflictInteractor.java
can the cohere api be referenced here? i need to double check

2024-12-01 03:41 UTC, utcjcao commented on src/main/java/usecase/delete/DeleteEventInteractor.java
if needed, add exception cases if an error occurs

2024-12-01 03:41 UTC, utcjcao commented on src/main/java/usecase/edit/EditInputData.java
add some spaces separating lines (for checkstyle)

2024-12-01 03:41 UTC, utcjcao commented on src/test/java/usecase/deleteevent/DeleteEventIntegrationTest.java
might need to format for newlines

2024-12-01 03:41 UTC, utcjcao commented on src/test/java/usecase/deleteevent/DeleteEventPresenterTest.java
watch out for newlines formatting. mightneed to trim

2024-12-01 03:41 UTC, utcjcao commented on src/test/java/usecase/edit/EditInteractorTest.java
might need to check for empty lists

2024-12-01 04:40 UTC, venniseho approved these changes
All the changes look good!!

2024-12-01 04:44 UTC, utcjcao requested changes
code looks good to merge 

delete cohere parser

2024-12-01 04:46 UTC, utcjcao approved these changes
amazing <3

2024-12-01 05:12 UTC, merged